# Generated by Django 4.2.6 on 2023-10-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Password',
        ),
    ]
