# Generated by Django 4.2.6 on 2023-10-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
