# Generated by Django 4.2.6 on 2023-10-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_user',
        ),
    ]
